/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CNAMERecordInitParameters struct {

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	Cname *string `json:"cname,omitempty" tf:"cname,omitempty"`

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type CNAMERecordObservation struct {

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	Cname *string `json:"cname,omitempty" tf:"cname,omitempty"`

	// (String) Always set to the fully qualified domain name of the record.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type CNAMERecordParameters struct {

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	// +kubebuilder:validation:Optional
	Cname *string `json:"cname,omitempty" tf:"cname,omitempty"`

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
	// +kubebuilder:validation:Required
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

// CNAMERecordSpec defines the desired state of CNAMERecord
type CNAMERecordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CNAMERecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CNAMERecordInitParameters `json:"initProvider,omitempty"`
}

// CNAMERecordStatus defines the observed state of CNAMERecord.
type CNAMERecordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CNAMERecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CNAMERecord is the Schema for the CNAMERecords API. Creates a CNAME type DNS record.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dns}
type CNAMERecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cname) || (has(self.initProvider) && has(self.initProvider.cname))",message="spec.forProvider.cname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CNAMERecordSpec   `json:"spec"`
	Status CNAMERecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CNAMERecordList contains a list of CNAMERecords
type CNAMERecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CNAMERecord `json:"items"`
}

// Repository type metadata.
var (
	CNAMERecord_Kind             = "CNAMERecord"
	CNAMERecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CNAMERecord_Kind}.String()
	CNAMERecord_KindAPIVersion   = CNAMERecord_Kind + "." + CRDGroupVersion.String()
	CNAMERecord_GroupVersionKind = CRDGroupVersion.WithKind(CNAMERecord_Kind)
)

func init() {
	SchemeBuilder.Register(&CNAMERecord{}, &CNAMERecordList{})
}
