/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PTRInitParameters struct {

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) The TTL of the record. Defaults to 3600.
	// The TTL of the record. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type PTRObservation struct {

	// (String) Always set to the fully qualified domain name of the record.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) The TTL of the record. Defaults to 3600.
	// The TTL of the record. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type PTRParameters struct {

	// (String) The name of the record. The zone argument will be appended to this value to create the full record path.
	// The name of the record. The `zone` argument will be appended to this value to create the full record path.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The canonical name this record will point to.
	// The canonical name this record will point to.
	// +kubebuilder:validation:Optional
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) The TTL of the record. Defaults to 3600.
	// The TTL of the record. Defaults to `3600`.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// +kubebuilder:validation:Required
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

// PTRSpec defines the desired state of PTR
type PTRSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PTRParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PTRInitParameters `json:"initProvider,omitempty"`
}

// PTRStatus defines the observed state of PTR.
type PTRStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PTRObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PTR is the Schema for the PTRs API. Creates a PTR type DNS record.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dns}
type PTR struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ptr) || (has(self.initProvider) && has(self.initProvider.ptr))",message="spec.forProvider.ptr is a required parameter"
	Spec   PTRSpec   `json:"spec"`
	Status PTRStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PTRList contains a list of PTRs
type PTRList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PTR `json:"items"`
}

// Repository type metadata.
var (
	PTR_Kind             = "PTR"
	PTR_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PTR_Kind}.String()
	PTR_KindAPIVersion   = PTR_Kind + "." + CRDGroupVersion.String()
	PTR_GroupVersionKind = CRDGroupVersion.WithKind(PTR_Kind)
)

func init() {
	SchemeBuilder.Register(&PTR{}, &PTRList{})
}
