apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "provider-dns.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  credentials: |
    {
      "rfc": {{ .Values.secret.rfc | quote }},
      "server": {{ .Values.realm.kdc | quote }},
      "realm": {{ .Values.realm.name | quote }},
      "username": {{ .Values.secret.username | quote }},
      "password": {{ .Values.secret.password | quote }}
    }
