apiVersion: a.dns.crossplane.io/v1alpha1
kind: RecordSet
metadata:
  annotations:
    meta.upbound.io/example-id: a/v1alpha1/recordset
  labels:
    testing.upbound.io/example-name: www
  name: www
spec:
  forProvider:
    addresses:
    - 192.168.0.1
    - 192.168.0.2
    - 192.168.0.3
    ttl: 300
    zone: example.com.
