/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ARecordSetInitParameters struct {

	// (Set of String) The IPv4 addresses this record set will point to.
	// The IPv4 addresses this record set will point to.
	// +listType=set
	Addresses []*string `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// (String) The name of the record set. The zone argument will be appended to this value to create the full record path.
	// The name of the record set. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type ARecordSetObservation struct {

	// (Set of String) The IPv4 addresses this record set will point to.
	// The IPv4 addresses this record set will point to.
	// +listType=set
	Addresses []*string `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the record set. The zone argument will be appended to this value to create the full record path.
	// The name of the record set. The `zone` argument will be appended to this value to create the full record path.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ARecordSetParameters struct {

	// (Set of String) The IPv4 addresses this record set will point to.
	// The IPv4 addresses this record set will point to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Addresses []*string `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// (String) The name of the record set. The zone argument will be appended to this value to create the full record path.
	// The name of the record set. The `zone` argument will be appended to this value to create the full record path.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The TTL of the record set. Defaults to 3600.
	// The TTL of the record set. Defaults to `3600`.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
	// +kubebuilder:validation:Required
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

// ARecordSetSpec defines the desired state of ARecordSet
type ARecordSetSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ARecordSetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ARecordSetInitParameters `json:"initProvider,omitempty"`
}

// ARecordSetStatus defines the observed state of ARecordSet.
type ARecordSetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ARecordSetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ARecordSet is the Schema for the ARecordSets API. Creates an A type DNS record set.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dns}
type ARecordSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.addresses) || (has(self.initProvider) && has(self.initProvider.addresses))",message="spec.forProvider.addresses is a required parameter"
	Spec   ARecordSetSpec   `json:"spec"`
	Status ARecordSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ARecordSetList contains a list of ARecordSets
type ARecordSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ARecordSet `json:"items"`
}

// Repository type metadata.
var (
	ARecordSet_Kind             = "ARecordSet"
	ARecordSet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ARecordSet_Kind}.String()
	ARecordSet_KindAPIVersion   = ARecordSet_Kind + "." + CRDGroupVersion.String()
	ARecordSet_GroupVersionKind = CRDGroupVersion.WithKind(ARecordSet_Kind)
)

func init() {
	SchemeBuilder.Register(&ARecordSet{}, &ARecordSetList{})
}
