/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AAAARecordSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ARecordSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MXRecordSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NSRecordSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SRVRecordSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TXTRecordSet) Hub() {}
